# Generated by Django 5.0.10 on 2025-02-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_monto_total_cicloahorro_monto_por_participante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanteciclo',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='gestion.cicloahorro'),
        ),
    ]
